name: continuous-integration
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v4
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          extensions: curl, intl, mbstring, simplexml
          php-version: latest
      - name: Run tests
        run: ./run.ps1 Test
